import type { CuratedModel } from '@interloom/protocol'

export const CURATED_MODELS: CuratedModel[] = [
  {
    id: 'qwen2.5-72b-q4',
    repoId: 'bartowski/Qwen2.5-72B-Instruct-GGUF',
    filename: 'Qwen2.5-72B-Instruct-Q4_K_M.gguf',
    displayName: 'Qwen 2.5 72B Instruct',
    sizeBytes: 47415715488,
    quant: 'Q4_K_M',
    minVramMB: 55552,
    tier: 'spark',
    blurb: 'Largest capable model for Spark; excellent reasoning and multilingual support with unified memory access.',
  },
  {
    id: 'llama3.3-70b-q4',
    repoId: 'bartowski/Llama-3.3-70B-Instruct-GGUF',
    filename: 'Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    displayName: 'Llama 3.3 70B Instruct',
    sizeBytes: 42520398816,
    quant: 'Q4_K_M',
    minVramMB: 50048,
    tier: 'spark',
    blurb: 'Strong code and math reasoning; efficient 70B model perfect for Spark unified memory.',
  },
  {
    id: 'qwen2.5-32b-q4',
    repoId: 'bartowski/Qwen2.5-32B-Instruct-GGUF',
    filename: 'Qwen2.5-32B-Instruct-Q4_K_M.gguf',
    displayName: 'Qwen 2.5 32B Instruct',
    sizeBytes: 19851336576,
    quant: 'Q4_K_M',
    minVramMB: 23424,
    tier: 'gpu-24gb',
    blurb: 'Balanced capability and speed for 24GB cards; excellent instruction-following and knowledge.',
  },
  {
    id: 'gemma2-27b-q4',
    repoId: 'bartowski/Gemma-2-27B-it-GGUF',
    filename: 'gemma-2-27b-it-Q4_K_M.gguf',
    displayName: 'Gemma 2 27B Instruct',
    sizeBytes: 16645381632,
    quant: 'Q4_K_M',
    minVramMB: 19680,
    tier: 'gpu-24gb',
    blurb: 'Efficient 27B model with strong factual accuracy; well-optimized for 24GB VRAM.',
  },
  {
    id: 'qwen2.5-7b-q4',
    repoId: 'bartowski/Qwen2.5-7B-Instruct-GGUF',
    filename: 'Qwen2.5-7B-Instruct-Q4_K_M.gguf',
    displayName: 'Qwen 2.5 7B Instruct',
    sizeBytes: 4683074240,
    quant: 'Q4_K_M',
    minVramMB: 5568,
    tier: 'gpu-10gb',
    blurb: 'Capable 7B fit for 10GB cards; excellent quality-to-size ratio with strong instruction adherence.',
  },
  {
    id: 'llama3.1-8b-q4',
    repoId: 'unsloth/Llama-3.1-8B-Instruct-GGUF',
    filename: 'Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    displayName: 'Llama 3.1 8B Instruct',
    sizeBytes: 4920739200,
    quant: 'Q4_K_M',
    minVramMB: 5824,
    tier: 'gpu-10gb',
    blurb: 'Solid mid-range performer; clean foundation model with strong code reasoning for 10GB tier.',
  },
  {
    id: 'phi3.5-mini-q4',
    repoId: 'bartowski/Phi-3.5-mini-Instruct-GGUF',
    filename: 'Phi-3.5-mini-instruct-Q4_K_M.gguf',
    displayName: 'Phi 3.5 Mini Instruct',
    sizeBytes: 2393232672,
    quant: 'Q4_K_M',
    minVramMB: 2880,
    tier: 'gpu-10gb',
    blurb: 'Tiny 3.5B model on 10GB; Microsoft research favorite for efficiency and instruction tasks.',
  },
  {
    id: 'qwen2.5-3b-q4',
    repoId: 'bartowski/Qwen2.5-3B-Instruct-GGUF',
    filename: 'Qwen2.5-3B-Instruct-Q4_K_M.gguf',
    displayName: 'Qwen 2.5 3B Instruct',
    sizeBytes: 1929903264,
    quant: 'Q4_K_M',
    minVramMB: 2304,
    tier: 'cpu',
    blurb: 'Lightweight 3B for CPU or low-VRAM deploy; solid instruct performance at minimal resource cost.',
  },
  {
    id: 'qwen2.5-1.5b-q4',
    repoId: 'lmstudio-community/Qwen2.5-1.5B-Instruct-GGUF',
    filename: 'Qwen2.5-1.5B-Instruct-Q4_K_M.gguf',
    displayName: 'Qwen 2.5 1.5B Instruct',
    sizeBytes: 986048512,
    quant: 'Q4_K_M',
    minVramMB: 1184,
    tier: 'cpu',
    blurb: 'Ultra-compact 1.5B; ideal edge or offline deployment with surprising fluency for size.',
  },
  {
    id: 'mistral-7b-q4',
    repoId: 'bartowski/Mistral-7B-Instruct-v0.3-GGUF',
    filename: 'Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
    displayName: 'Mistral 7B Instruct v0.3',
    sizeBytes: 4372812000,
    quant: 'Q4_K_M',
    minVramMB: 5184,
    tier: 'gpu-10gb',
    blurb: 'Fast, efficient 7B alternative; excellent instruction-tuned baseline for inference speed.',
  },
]
